package com.barclays.categories.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import com.barclays.categories.model.CategoriesRequest;
import com.barclays.categories.model.CategoriesResponse;
import com.barclays.categories.service.ICategoriesService;
import com.barclays.categories.validator.CategoriesRequestValidator;

@RestController
@RequestMapping("/v1")
public class CategoriesController {
	/*
	 * Request Header Summary (used for API communication):
	 *
	 * 1. client_id: - Identifies the source of the request (e.g., "web", "mobile").
	 * - Helps the server apply logic specific to the client type.
	 *
	 * 2. channel_id: - Indicates the transaction context or channel (e.g.,
	 * "online", "offline"). - online(e-commerce, web chat, or digital app) -
	 * offline(store, POS terminal, or field device)
	 *
	 * 3. request_id: - Unique alphanumeric ID (e.g., "abc123xyz"), should be
	 * generated by the client per request. - Server can fallback-generate if
	 * missing.
	 *
	 * 4. message_timestamp: - Timestamp of when the client generated the request. -
	 * Format: DD-MM-YY HH:MM:SS - Used for ordering, debugging, and time
	 * validation.
	 */

	@Autowired
	ICategoriesService iCategoriesService;

	@Autowired
	CategoriesRequestValidator categoriesRequestValidator;

	@GetMapping("/categories/{cardNo}")
	public ResponseEntity<CategoriesResponse> getCategories(@PathVariable(value ="cardNo") String cardNo,
			@RequestHeader(value = "client_id", required = false) String client_id,
			@RequestHeader(value = "channel_id", required = false) String channelId,
			@RequestHeader(value = "request_id", required = false) String requestId,
			@RequestHeader(value = "message_timestamp", required = false) String message_ts) {

		// get the request from the consumer
		CategoriesRequest categoriesRequest = new CategoriesRequest();
		categoriesRequest.setCardNum(cardNo);
		categoriesRequest.setClientId(client_id);
		categoriesRequest.setChannelId(channelId);
		categoriesRequest.setReqId(requestId);
		categoriesRequest.setMsgTs(message_ts);

		// Validate the Request
		categoriesRequestValidator.validateCategoriesRequest(categoriesRequest);
		CategoriesResponse categories = iCategoriesService.getCategories(categoriesRequest);

		return ResponseEntity.ok(categories);

	}
}
